const resources = {
  en: {
    translation: {
      "label_loading": "Loading...",
      "label_item": "Item",
      "title_app": "Pricey by wlap.pl",
      "nav_home": "Home",
      "nav_yourlist": "Your list",
      "nav_aboutus": "About us",
      "nav_privacy": "Privacy policy",
      "nav_install": "How to install",
      "button_new_product": "New Product",
      "button_update_price": "Update Price",
      "label_search": "Search",
      "button_copy": "Copy",
      "button_back": "Back",
      "label_name": "Name",
      "label_store": "Store",
      "label_price": "Price",
      "label_posted": "Posted",
      "label_coupon": "Coupon",
      "label_bulk": "Bulk",
      "label_selected": "Selected",
      "label_more": "Details",
      "help_name": "If product already exists open its history and update price",
      "help_store": "Keep store name consistent",
      "help_decimal": "Use dot as decimal point",
      "help_membership": "Members price",
      "help_bulk": "Price in bulk",
      "button_cancel": "Cancel",
      "button_save": "Save",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/google-play/refs/heads/main/pricey/data/privacy-policy-en",
      "url_get": "https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png",
      "meta_description": "Record grocery prices, invite your firends, check what others submit, look up the history or observe cost of living rise",
      "meta_keywords": "pwa, app, application, groceries, shopping, price, cost, list, shop, market, supermarket",
      "message_warning": "Data seen in this application is for information purposes only and are not meant to be used in trade. We do all we can to keep them up to date but we can't guarantee for them to be always accurate. If you appreciate the work we do you can help us or give a donation.",
      "button_gotit": "Got it"
    }
  },
  pl: {
    translation: {
      "label_loading": "Wczytuję...",
      "label_item": "Produkt",
      "title_app": "Cennik od wlap.pl",
      "nav_home": "Strona główna",
      "nav_yourlist": "Twoja lista",
      "nav_aboutus": "O nas",
      "nav_privacy": "Polityka prywatności",
      "nav_install": "Jak zainstalować",
      "button_new_product": "Nowy produkt",
      "button_update_price": "Aktualizuj cenę",
      "label_search": "Szukaj",
      "button_copy": "Kopiuj",
      "button_back": "Powrót",
      "label_name": "Nazwa",
      "label_store": "Sklep",
      "label_price": "Cena",
      "label_posted": "Dodano",
      "label_coupon": "Z kartą",
      "label_bulk": "Kilka",
      "label_selected": "Wybrane",
      "label_more": "Historia",
      "help_name": "Jeśli produkt istnieje otwórz jego historię i zaktualizuj cenę",
      "help_store": "Utrzymuj nazwy sklepów jednakowe",
      "help_decimal": "Użyj kropki jako przecinka",
      "help_membership": "Cena z kartą",
      "help_bulk": "Przy zakupie większej ilości",
      "button_cancel": "Zaniechaj",
      "button_save": "Zachowaj",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/google-play/refs/heads/main/pricey/data/privacy-policy-pl",
      "url_get": "https://play.google.com/intl/en_us/badges/static/images/badges/pl_badge_web_generic.png",
      "meta_description": "Zapisuj ceny produktów w sklepach, zaproś znajomych, sprawdzaj co oni przesłali, porównuj promocje oraz ceny zakupów w czasie",
      "meta_keywords": "pwa, apka, aplikacja, zakupy, cena, cennik, koszt, lista, sklep, market, supermarket",
      "message_warning": "Dane prezentowane w aplikacji mają charakter wyłącznie informacyjny i pochodzą od użytkowników którzy zyskują za to dostęp do nowych funkcji. Odwiedź tiktok.com/@czarna.marchewka aby poznać wszystkie możliwości. Pliki cookies są wykorzystywane do personalizacji a szczegóły znajdziesz w Polityce Prywatności.",
      "button_gotit": "Rozumiem"
    }
  }
}
