const resources = {
  en: {
    translation: {
      "label_loading": "Loading...",
      "label_item": "Item",
      "title_app": "Pricey the app by wlap.pl",
      "nav_yourlist": "Your list",
      "nav_aboutus": "About us",
      "nav_privacy": "Privacy policy",
      "button_new_product": "New Product",
      "button_update_price": "Update Price",
      "label_search": "Search",
      "button_copy": "Copy",
      "button_back": "Back",
      "label_name": "Name",
      "label_store": "Store",
      "label_price": "Price",
      "label_posted": "Posted",
      "label_coupon": "Coupon",
      "label_bulk": "Bulk",
      "label_selected": "Selected",
      "label_more": "Details",
      "button_cancel": "Cancel",
      "button_save": "Save",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/google-play/refs/heads/main/pricey/data/privacy-policy-en",
      "url_get": "https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png",
      "meta_description": "Record grocery prices, invite your firends, check what others submit, look up the history or observe cost of living rise",
      "meta_keywords": "groceries, shopping, price, list"
    }
  },
  pl: {
    translation: {
      "label_loading": "Wczytuję...",
      "label_item": "Produkt",
      "title_app": "apka Pricey od wlap.pl",
      "nav_yourlist": "Twoja lista",
      "nav_aboutus": "O nas",
      "nav_privacy": "Polityka prywatności",
      "button_new_product": "Nowy produkt",
      "button_update_price": "Aktualizuj cenę",
      "label_search": "Szukaj",
      "button_copy": "Kopiuj",
      "button_back": "Powrót",
      "label_name": "Nazwa",
      "label_store": "Sklep",
      "label_price": "Cena",
      "label_posted": "Dodano",
      "label_coupon": "Z kartą",
      "label_bulk": "Kilka",
      "label_selected": "Wybrane",
      "label_more": "Historia",
      "button_cancel": "Zaniechaj",
      "button_save": "Zachowaj",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/google-play/refs/heads/main/pricey/data/privacy-policy-pl",
      "url_get": "https://play.google.com/intl/en_us/badges/static/images/badges/pl_badge_web_generic.png",
      "meta_description": "Zapisuj ceny produktów w sklepach, zaproś znajomych, sprawdzaj co oni przesłali, porównuj promocje oraz ceny zakupów w czasie",
      "meta_keywords": "zakupy, cena, lista, sklep, koszt"
    }
  }
}