const resources = {
  en: {
    translation: {
      "title_home": "wlap.pl",
      "description_copyright": "wlap.pl, 2025",
      "description_guide": "",
      "button_backtotop": "Back to top",
      "button_home": "Home",
      "title_contact": "Custom orders and questions",
      "subtitle_contact": "Contact",
      "description_contact": "Questions or custom orders see Contant section",
      "link_emailus": "Email us",
      "title_products": "Mobile and web apps",
      "description_products": "We create mobile apps for Android and web apps that you can run on any platform with access to the internet",
      "button_googleplay": "Google Play",
      "button_howto": "How to",
      "button_online": "Online",
      "button_get": "Install",
      "name_pricey": "Pricey",
      "description_pricey": "Record grocery prices, invite your firends, check what others submit, look up the history or observe cost of living rise",
      "name_busstop": "BusStop",
      "description_busstop": "Bus schedule with map",
      "name_myparish": "My Parish",
      "description_myparish": "Find your church on a map, get the directions, read the bulletin, check the mass times or pray online",
      "name_talkietalkie": "TalkieTalkie",
      "description_talkietalkie": "Send and receive voice messages over WiFi between two phones without the network connection in Walkie-talkie style",
      "item_offer1": "",
      "item_offer2": "",
      "item_offer3": "",
      "item_offer4": "",
      "item_offer5": "",
      "item_offer6": "",
      "item_offer7": "",
      "button_back": "Back",
      "title_offer": "Offer",
      "subtitle_products": "Products",
      "subtitle_offer": "Services",
      "carousel_image": "Screen no",
      "header_install": "How to install PWA apps",
      "description_install": "Select an item below to read installation steps for the platform on an exmaple browser. In other browsers this process looks simmilar but menu items and buttons might be named differently.",
      "accordion_header_iphone": "iPhone (Safari)",
      "accordion_intro_iphone": "Start by opening https://wlap.pl/ in Safari",
      "accordion_contd_iphone": "",
      "accordion_header_android": "Android (e.g. Chrome)",
      "accordion_intro_android": "Start by opening https://wlap.pl/ in a browser",
      "accordion_contd_android": "",
      "accordion_header_windows": "Windows (e.g. Chrome)",
      "accordion_intro_windows": "Start by opening https://wlap.pl/ in a browser",
      "accordion_contd_windows": ""
    }
  },
  pl: {
    translation: {
      "title_home": "wlap.pl",
      "description_copyright": "wlap.pl, 2025",
      "description_guide": "",
      "button_backtotop": "W górę",
      "button_home": "Strona głowna",
      "title_contact": "Pytania i zamówienia",
      "subtitle_contact": "Kontakt",
      "description_contact": "Pytania oraz zlecenia proszę kierować na adres e-mail",
      "link_emailus": "Napisz do nas",
      "title_products": "Aplikacje mobilne i internetowe",
      "description_products": "Zajmujemy się tworzeniem aplikacji mobilnych na system Android oraz aplikacji internetowych które można używać na dowolnej platformie z dostępem do internetu",
      "button_googleplay": "Sklep Play",
      "button_howto": "Przewodnik",
      "button_online": "Przejdź",
      "button_get": "Pobierz",
      "name_pricey": "Pricey",
      "description_pricey": "Zachowuj ceny produktów, zaproś przyjaciół, sprawdzaj co inni przesłali, przeglądaj historię lub obserwuj wzrost kosztów życia",
      "name_busstop": "BusStop",
      "description_busstop": "Rozkład jazdy autobusów z mapą",
      "name_myparish": "Moja Parafia",
      "description_myparish": "Znajdź twój kościół na mapie, zobacz dojazd, czytaj ogłoszenia parafialne, sprawdź harmonogram mszy, oglądaj transmisje",
      "name_talkietalkie": "TalkieTalkie",
      "description_talkietalkie": "Wysyłaj i odbieraj wiadomości głosowe przy pomocy WiFi pomiędzy dwoma telefonami bez połączenia sieciowego w stylu Walkie-talkie",
      "item_offer1": "Aplikacje mobilne i internetowe",
      "item_offer2": "Rozszerzenia do Office, Chrome, Visual Studio Code itp",
      "item_offer3": "Zabezpieczanie połączeń sieciowych",
      "item_offer4": "Witryny internetowe",
      "item_offer5": "Rozkłady jazdy",
      "item_offer6": "Domowe sieci komputerowe",
      "item_offer7": "Testowanie rozwiązań informatycznych",
      "title_offer": "Oferta",
      "subtitle_products": "Produkty",
      "subtitle_offer": "Usługi",
      "button_back": "Powrót",
      "carousel_image": "Krok nr",
      "header_install": "Jak zainstalować aplikacje typu PWA",
      "description_install": "Poniżej przedstawiamy instrukcje instalacji na wybranych platformach przy użyciu przykładowych przeglądarek. Proces przebiega podobnie w innych przeglądarkach, różnić mogą się nazwy menu i przycisków. Obok obrazy pokazujące kolejne kroki, użyj strzałek aby przełączać.",
      "accordion_header_iphone": "iPhone (Safari)",
      "accordion_intro_iphone": "Uruchom Safari i przejdź pod adres https://wlap.pl/",
      "accordion_contd1_iphone": "Na stronie głównej wybierz aplikację którą chcesz zainstalować i przejdź do niej (Krok nr 1)",
      "accordion_contd2_iphone": "Otwórz menu przeglądarki i wybierz 'Dodaj do ekranu głównego' (Krok nr 2)",
      "accordion_contd3_iphone": "Na ekranie z opisem aplikacji wybierz 'Dodaj' (Krok nr 3)",
      "accordion_contd4_iphone": "Zamknij Safari, na ekranie głównym ujrzysz ikonę zainstalowanej aplikacji (Krok nr 4)",
      "accordion_header_android": "Android (Chrome)",
      "accordion_intro_android": "Uruchom Chrome i przejdź pod adres https://wlap.pl/",
      "accordion_contd1_android": "Na stronie głównej wybierz aplikację którą chcesz zainstalować i przejdź do niej (Krok nr 1)",
      "accordion_contd2_android": "Otwórz menu przeglądarki i wybierz 'Dodaj do ekranu głównego' (Krok nr 2)",
      "accordion_contd3_android": "Na ekranie z opisem aplikacji wybierz 'Zainstaluj' (Krok nr 3)",
      "accordion_contd4_android": "Zamknij Chrome, na ekranie głównym ujrzysz ikonę zainstalowanej aplikacji (Krok nr 4)",
      "accordion_header_windows": "Windows (Chrome)",
      "accordion_intro_windows": "Uruchom Chrome i przejdź pod adres https://wlap.pl/",
      "accordion_contd1_windows": "Na stronie głównej wybierz aplikację którą chcesz zainstalować i przejdź do niej (Krok nr 1)",
      "accordion_contd2_windows": "Otwórz menu przeglądarki i wybierz 'Zainstaluj ...' (Krok nr 2)",
      "accordion_contd3_windows": "W oknie dialogowym wybierz 'Zainstaluj' (Krok nr 3)",
      "accordion_contd4_windows": "Zamknij Chrome, na pasku zadań ujrzysz ikonę zainstalowanej aplikacji (Krok nr 4)"
    }
  }
}