const resources = {
  en: {
    translation: {
      "button_online": "Online",
      "button_back": "Back",
      "title_home": "wlap.pl",
      "title_offer": "Offer",
      "title_products": "Products",
      "title_contact": "Contact",
      "subtitle_offer": "Services",
      "subtitle_products": "Mobile and web apps",
      "subtitle_contact": "How to order",
      "name_pricey": "Pricey",
      "name_busstop": "BusStop",
      "name_myparish": "My Parish",
      "description_pricey": "Porównywarka cenowa z historią",
      "description_busstop": "Rozkład jazdy autobusów z mapą",
      "description_myparish": "Katalog stron parafialnych z mapą",
      "description_contact": "Pytania oraz zamówienia proszę kierować na adres e-mail:",
      "item_offer1": "Aplikacje mobilne i internetowe",
      "item_offer2": "Rozszerzenia do Office, Chrome, Visual Studio Code itp",
      "item_offer3": "Zabezpieczanie połączeń sieciowych",
      "item_offer4": "Witryny internetowe",
      "item_offer5": "Rozkłady jazdy",
      "item_offer6": "Domowe sieci komputerowe",
      "item_offer7": "Testowanie rozwiązań informatycznych",
      "button_backtotop": "Back to top",
      "description_copyright": "wlap.pl, 2024",
      "description_guide": "",
      "button_get": "Get",
      "button_googleplay": "Google Play",
      "button_action": "",
      "link_emailus": "Email us"
    }
  },
  pl: {
    translation: {
      "button_online": "Przejdź",
      "title_home": "wlap.pl",
      "title_offer": "Oferta",
      "title_products": "Produkty",
      "title_contact": "Kontakt",
      "subtitle_offer": "Usługi",
      "subtitle_products": "Aplikacje mobilne i internetowe",
      "subtitle_contact": "Jak złożyć zamówienie",
      "button_back": "Powrót",
      "name_pricey": "Pricey",
      "name_busstop": "BusStop",
      "name_myparish": "Moja Parafia",
      "description_pricey": "Porównywarka cenowa z historią",
      "description_busstop": "Rozkład jazdy autobusów z mapą",
      "description_myparish": "Katalog stron parafialnych z mapą",
      "description_contact": "Pytania oraz zamówienia proszę kierować na adres e-mail:",
      "item_offer1": "Aplikacje mobilne i internetowe",
      "item_offer2": "Rozszerzenia do Office, Chrome, Visual Studio Code itp",
      "item_offer3": "Zabezpieczanie połączeń sieciowych",
      "item_offer4": "Witryny internetowe",
      "item_offer5": "Rozkłady jazdy",
      "item_offer6": "Domowe sieci komputerowe",
      "item_offer7": "Testowanie rozwiązań informatycznych",
      "button_backtotop": "W górę",
      "description_copyright": "wlap.pl, 2024",
      "description_guide": "",
      "button_get": "Pobierz",
      "button_googleplay": "Sklep Play",
      "button_action": "",
      "link_emailus": "Napisz do nas"
    }
  }
}