-- ALTER TABLE `CENA` AUTO_INCREMENT = 1;

-- DROP TRIGGER `CENA_DODANO_DEFAULT`;

-- DROP TABLE `CENA`;

/* CREATE TABLE `CENA` (
  `ID` BIGINT AUTO_INCREMENT,
  `PRODUKT` VARCHAR(1024) NOT NULL,
  `SKLEP` VARCHAR(1024) NOT NULL,
  `CENA` FLOAT NOT NULL,
  `KRAJ` VARCHAR(5) NOT NULL,
  `UZYTKOWNIK` VARCHAR(36) NOT NULL,
  `DODANO` DATETIME,
  CONSTRAINT `PK_Cena` PRIMARY KEY (`ID`)
); */

-- CREATE TRIGGER `CENA_DODANO_DEFAULT` BEFORE INSERT ON `CENA`
--   FOR EACH ROW SET NEW.`DODANO` = CURRENT_TIMESTAMP;
