const resources = {
  en: {
    translation: {
      "title_app": "My Parish by wlap.pl",
      "see_link": "See",
      "list_schedule": "Schedule",
      "list_announcement": "Announcement",
      "list_contact": "Contact",
      "list_other": "Other",
      "list_live": "Live",
      "list_directions": "Route",
      "list_select": "Select",
      "nav_your": "Your",
      "nav_list": "List",
      "nav_map": "Map",
      "nav_news": "News",
      "nav_aboutus": "About us",
      "nav_privacy": "Privacy policy",
      "nav_install": "How to install",
      "label_search": "Search",
      "label_live": "Live",
      "label_active": "Active",
      "button_back": "Back",
      "overlay_active": "Active",
      "overlay_inactive": "Inactive",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/google-play/refs/heads/main/myparish/data/privacy-policy-en",
      "url_get": "https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png",
      "meta_description": "Find your church on a map, get the directions, read the bulletin, check the mass times or pray online",
      "meta_keywords": "pwa, app, church, catholic, mass, parish, cemetery, map, live, news",
      "label_missing": "Parish data missing"
    }
  },
  pl: {
    translation: {
      "title_app": "Moja Parafia od wlap.pl",
      "see_link": "Zobacz",
      "list_schedule": "Intencje",
      "list_announcement": "Ogłoszenia",
      "list_contact": "Kontakt",
      "list_other": "Cmentarz",
      "list_live": "Transmisja",
      "list_directions": "Dojazd",
      "list_select": "Wybierz",
      "nav_your": "Twoja",
      "nav_list": "Lista",
      "nav_map": "Mapa",
      "nav_news": "Media",
      "nav_aboutus": "O nas",
      "nav_privacy": "Polityka prywatności",
      "nav_install": "Jak zainstalować",
      "label_search": "Szukaj",
      "label_live": "Transmisja",
      "label_active": "Nadchodzące",
      "button_back": "Powrót",
      "overlay_active": "Nadchodzące",
      "overlay_inactive": "Pozostałe",
      "url_privacy": "https://raw.githubusercontent.com/wojtekl/google-play/refs/heads/main/myparish/data/privacy-policy-pl",
      "url_get": "https://play.google.com/intl/en_us/badges/static/images/badges/pl_badge_web_generic.png",
      "meta_description": "Znajdź twój kościół na mapie, zobacz dojazd, czytaj ogłoszenia parafialne, sprawdź harmonogram mszy, oglądaj transmisje",
      "meta_keywords": "pwa, apka, kościół, katolicki, msza, parafia, cmentarz, mapa, transmisja, wiadomości",
      "label_missing": "Brak danych parafii"
    }
  }
}